[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
maxUploadSize = 1000
enableCORS = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false 